# Generated by Django 5.1.2 on 2024-11-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfcstoreapp', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
